# The URL the site will be built for
base_url = "http://localhost:1111"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Hi,"
theme = "zola-hook"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
links = [
    { title = "mail", href = "buysedev@proton.me" },
    { title = "github", href = "https://github.com/solargc" },
]
